# Site settings
title: POST 8000
subtitle: Foundations of Social Science Research for Public Policy
description: "Quantitative public policy analysis shares important foundations with a standard upper-division or graduate-level course on inferential statistics, but the objectives have important differences. A statistics class may make greater emphasis of statistical inference from sample statistics to population parameters under known assumptions (e.g. random sampling, central limit theorem). A quantitative public policy analysis course may care more about causal inference and the scope of treatment effects. Both inform each other, but speak to different audiences. This class will bring in some foundation components of a statistics class and tailor it for a public policy audience. It starts with rudimentary statistics, assuming a policy audience may not be accustomed to thinking of policy analysis quantitatively. It proceeds to basic tests of difference and association. It builds toward more sophisticated research designs, like regression discontinuities and instrumental variables. It then discusses what to do when data are not normally distributed. It concludes with some finer, but important, points of interest to the professor but of value for the student (i.e. quantities of interest, replication, and Bayesian perspectives). This class aims to broadly prepare students for quantitative public policy analysis for research in and out the academy."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://post8000.svmiller.com" # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/post8000/blob/master/syllabus/post8000-spring2020-syllabus.pdf"
githubdir: "svmiller/post8000"

# Author/user information
email: svmille@clemson.edu
twitter_username: stevenvmiller
github_username:  svmiller
authorurl: "http://svmiller.com"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
